name: pin_code_fields
description: A flutter package which will help you to generate pin code fields. Can be useful for OTP for example.
version: 2.2.1
author: "A.K.M. Saiful Islam <saifulislamadar@gmail.com>"
homepage: https://github.com/adar2378
repository: https://github.com/adar2378/pin_code_fields

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  charts_flutter: ^0.6.0
  flare_flutter: ^1.7.1
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  uses-material-design: true
  assets:
    - assets/verify.png
    - assets/otp.flr
    - assets/btc.png
    - assets/cm1.jpeg
    - assets/cm2.jpeg
    - assets/cm3.jpeg
    - assets/cm4.jpeg
    - assets/cm5.jpeg
    - assets/cm6.jpeg
    - assets/cm7.jpeg
    - assets/cm8.jpeg
    - assets/cm9.jpeg
    - assets/cm0.jpeg
    - assets/btc.png
    - assets/ltc.png
    - assets/xmr.png
    - assets/xrp.png
    - assets/eth.png
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
